### ISSUE TITLE
训练时出现的问题

### ISSUE THREAD

**Issue by gavenswang** [FreeApe/VGG-or-MobileNet-SSD#3]
你好，首先非常谢谢您的研究工作

但是我在拿您的模型就行微调时出现了问题。您网络中class_num=11，我想训练voc的20类，所以就把最后一层修改了一下，然后截取您提供的预训练模型的前17层参数，在这个基础上进行训练，出现以下错误：

F0207 11:29:41.736740  9502 multibox_loss_layer.cpp:141] Check failed: num_priors_ * num_classes_ == bottom[1]->channels() (41895 vs. 21945) Number of priors must match number of confidence predictions.
*** Check failure stack trace: ***
    @     0x7f926fb6c5cd  google::LogMessage::Fail()
    @     0x7f926fb6e433  google::LogMessage::SendToLog()
    @     0x7f926fb6c15b  google::LogMessage::Flush()
    @     0x7f926fb6ee1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f92702823b2  caffe::MultiBoxLossLayer<>::Reshape()
    @     0x7f9270329f26  caffe::Net<>::Init()
    @     0x7f927032b7a1  caffe::Net<>::Net()
    @     0x7f927033dc1a  caffe::Solver<>::InitTrainNet()
    @     0x7f927033f027  caffe::Solver<>::Init()
    @     0x7f927033f3ca  caffe::Solver<>::Solver()
    @     0x7f927035b009  caffe::Creator_RMSPropSolver<>()
    @           0x40c22a  train()
    @           0x4088f8  main
    @     0x7f926e298830  __libc_start_main
    @           0x4091c9  _start
    @              (nil)  (unknown)
Aborted (core dumped)
不知道为什么priors和confidence参数不匹配。网络中其他的参数我都没有进行修改，经计算发现21945*21/11 = 41895.按道理说我只训练最后一层，那么class_num可以随意修改的呀，只要数据正确。特此请教，出现这种情况的原因是什么？

**Comment by FreeApe** [comment]
你可以看看prior那层相关的源代码就明白了。相关的prior层也要做修改的。

**Comment by Francoforever** [comment]
"经计算发现21945*21/11 = 41895"。道理我都懂，但这个好像不等。
